
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook worldNotebook;

	private global::Gtk.Fixed worldLayout;

	private global::Gtk.EventBox worldImageEventBox;

	private global::Gtk.Image worldImage;

	private global::Gtk.Button RunButton;

	private global::Gtk.Button StopButton;

	private global::Gtk.Button SaveButton;

	private global::Gtk.ComboBox ColonyTypeList;

	private global::Gtk.Label ColonyTypeLabel;

	private global::Gtk.ColorButton ColonyColor;

	private global::Gtk.Label ColonyColorLabel;

	private global::Gtk.Label ParameterLabel;

	private global::Gtk.ComboBox ParameterList;

	private global::Gtk.Label StringValueLabel;

	private global::Gtk.Entry StringValue;

	private global::Gtk.Label ParameterNumericLabel;

	private global::Gtk.SpinButton NumericValue;

	private global::Gtk.Label worldLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 1280;
		this.HeightRequest = 720;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.worldNotebook = new global::Gtk.Notebook();
		this.worldNotebook.WidthRequest = 1280;
		this.worldNotebook.HeightRequest = 720;
		this.worldNotebook.CanFocus = true;
		this.worldNotebook.Name = "worldNotebook";
		this.worldNotebook.CurrentPage = 0;
		this.worldNotebook.ShowBorder = false;
		// Container child worldNotebook.Gtk.Notebook+NotebookChild
		this.worldLayout = new global::Gtk.Fixed();
		this.worldLayout.Name = "worldLayout";
		this.worldLayout.HasWindow = false;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.worldImageEventBox = new global::Gtk.EventBox();
		this.worldImageEventBox.WidthRequest = 800;
		this.worldImageEventBox.HeightRequest = 600;
		this.worldImageEventBox.Name = "worldImageEventBox";
		// Container child worldImageEventBox.Gtk.Container+ContainerChild
		this.worldImage = new global::Gtk.Image();
		this.worldImage.WidthRequest = 800;
		this.worldImage.HeightRequest = 600;
		this.worldImage.CanFocus = true;
		this.worldImage.Name = "worldImage";
		this.worldImageEventBox.Add(this.worldImage);
		this.worldLayout.Add(this.worldImageEventBox);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.worldImageEventBox]));
		w2.X = 20;
		w2.Y = 20;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.RunButton = new global::Gtk.Button();
		this.RunButton.Name = "RunButton";
		this.RunButton.UseUnderline = true;
		this.RunButton.FocusOnClick = false;
		this.RunButton.Label = global::Mono.Unix.Catalog.GetString("Run");
		this.worldLayout.Add(this.RunButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.RunButton]));
		w3.X = 20;
		w3.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.StopButton = new global::Gtk.Button();
		this.StopButton.Name = "StopButton";
		this.StopButton.UseUnderline = true;
		this.StopButton.FocusOnClick = false;
		this.StopButton.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.worldLayout.Add(this.StopButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.StopButton]));
		w4.X = 60;
		w4.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.SaveButton = new global::Gtk.Button();
		this.SaveButton.Name = "SaveButton";
		this.SaveButton.UseUnderline = true;
		this.SaveButton.FocusOnClick = false;
		this.SaveButton.Label = global::Mono.Unix.Catalog.GetString("Save");
		this.worldLayout.Add(this.SaveButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.SaveButton]));
		w5.X = 105;
		w5.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ColonyTypeList = global::Gtk.ComboBox.NewText();
		this.ColonyTypeList.WidthRequest = 300;
		this.ColonyTypeList.Name = "ColonyTypeList";
		this.worldLayout.Add(this.ColonyTypeList);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ColonyTypeList]));
		w6.X = 850;
		w6.Y = 40;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ColonyTypeLabel = new global::Gtk.Label();
		this.ColonyTypeLabel.Name = "ColonyTypeLabel";
		this.ColonyTypeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Colony Type</b>");
		this.ColonyTypeLabel.UseMarkup = true;
		this.worldLayout.Add(this.ColonyTypeLabel);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ColonyTypeLabel]));
		w7.X = 850;
		w7.Y = 20;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ColonyColor = new global::Gtk.ColorButton();
		this.ColonyColor.WidthRequest = 300;
		this.ColonyColor.CanFocus = true;
		this.ColonyColor.Events = ((global::Gdk.EventMask)(784));
		this.ColonyColor.Name = "ColonyColor";
		this.worldLayout.Add(this.ColonyColor);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ColonyColor]));
		w8.X = 850;
		w8.Y = 100;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ColonyColorLabel = new global::Gtk.Label();
		this.ColonyColorLabel.Name = "ColonyColorLabel";
		this.ColonyColorLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Color</b>");
		this.ColonyColorLabel.UseMarkup = true;
		this.worldLayout.Add(this.ColonyColorLabel);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ColonyColorLabel]));
		w9.X = 850;
		w9.Y = 80;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ParameterLabel = new global::Gtk.Label();
		this.ParameterLabel.Name = "ParameterLabel";
		this.ParameterLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Parameter</b>");
		this.ParameterLabel.UseMarkup = true;
		this.worldLayout.Add(this.ParameterLabel);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ParameterLabel]));
		w10.X = 850;
		w10.Y = 140;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ParameterList = global::Gtk.ComboBox.NewText();
		this.ParameterList.WidthRequest = 300;
		this.ParameterList.Name = "ParameterList";
		this.worldLayout.Add(this.ParameterList);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ParameterList]));
		w11.X = 850;
		w11.Y = 160;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.StringValueLabel = new global::Gtk.Label();
		this.StringValueLabel.Name = "StringValueLabel";
		this.StringValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Parameter string value</b>");
		this.StringValueLabel.UseMarkup = true;
		this.worldLayout.Add(this.StringValueLabel);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.StringValueLabel]));
		w12.X = 850;
		w12.Y = 200;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.StringValue = new global::Gtk.Entry();
		this.StringValue.WidthRequest = 300;
		this.StringValue.CanFocus = true;
		this.StringValue.Name = "StringValue";
		this.StringValue.IsEditable = true;
		this.StringValue.InvisibleChar = '●';
		this.worldLayout.Add(this.StringValue);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.StringValue]));
		w13.X = 850;
		w13.Y = 220;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ParameterNumericLabel = new global::Gtk.Label();
		this.ParameterNumericLabel.Name = "ParameterNumericLabel";
		this.ParameterNumericLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Parameter numeric value</b>");
		this.ParameterNumericLabel.UseMarkup = true;
		this.worldLayout.Add(this.ParameterNumericLabel);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ParameterNumericLabel]));
		w14.X = 850;
		w14.Y = 260;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.NumericValue = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.NumericValue.WidthRequest = 300;
		this.NumericValue.CanFocus = true;
		this.NumericValue.Name = "NumericValue";
		this.NumericValue.Adjustment.PageIncrement = 10D;
		this.NumericValue.ClimbRate = 1D;
		this.NumericValue.Digits = ((uint)(2));
		this.NumericValue.Numeric = true;
		this.worldLayout.Add(this.NumericValue);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.NumericValue]));
		w15.X = 850;
		w15.Y = 280;
		this.worldNotebook.Add(this.worldLayout);
		// Notebook tab
		this.worldLabel = new global::Gtk.Label();
		this.worldLabel.Name = "worldLabel";
		this.worldLabel.LabelProp = global::Mono.Unix.Catalog.GetString("World");
		this.worldNotebook.SetTabLabel(this.worldLayout, this.worldLabel);
		this.worldLabel.ShowAll();
		this.Add(this.worldNotebook);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 1280;
		this.DefaultHeight = 720;
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.worldImageEventBox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnWorldImageEventBoxButtonPressEvent);
		this.worldImageEventBox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnWorldImageEventBoxButtonReleaseEvent);
		this.worldImageEventBox.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler(this.OnWorldImageEventBoxMotionNotifyEvent);
		this.RunButton.Clicked += new global::System.EventHandler(this.OnRunButtonClicked);
		this.StopButton.Clicked += new global::System.EventHandler(this.OnStopButtonClicked);
		this.SaveButton.Clicked += new global::System.EventHandler(this.OnSaveButtonClicked);
		this.ColonyTypeList.Changed += new global::System.EventHandler(this.OnColonyTypeListChanged);
		this.ParameterList.Changed += new global::System.EventHandler(this.OnParameterListChanged);
		this.StringValue.Changed += new global::System.EventHandler(this.OnStringValueChanged);
		this.NumericValue.ValueChanged += new global::System.EventHandler(this.OnNumericValueValueChanged);
	}
}
