
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.Notebook worldNotebook;

	private global::Gtk.Fixed worldLayout;

	private global::Gtk.EventBox worldImageEventBox;

	private global::Gtk.Image worldImage;

	private global::Gtk.Button RunButton;

	private global::Gtk.Button StopButton;

	private global::Gtk.Button SaveButton;

	private global::Gtk.ComboBox ColonyTypeList;

	private global::Gtk.Label ColonyTypeLabel;

	private global::Gtk.ColorButton ColonyColor;

	private global::Gtk.Label ColonyColorLabel;

	private global::Gtk.Label ParameterLabel;

	private global::Gtk.ComboBox ParameterList;

	private global::Gtk.Label StringValueLabel;

	private global::Gtk.Entry StringValue;

	private global::Gtk.Label ParameterNumericLabel;

	private global::Gtk.SpinButton NumericValue;

	private global::Gtk.Image LoadedImage;

	private global::Gtk.Label LoadedImageLabel;

	private global::Gtk.Button LoadImageButton;

	private global::Gtk.Button AddImageButton;

	private global::Gtk.CheckButton Gradient;

	private global::Gtk.ToggleButton ShowColonies;

	private global::Gtk.Button ClearButton;

	private global::Gtk.Label NeighborhoodLabel;

	private global::Gtk.CheckButton TL;

	private global::Gtk.CheckButton TM;

	private global::Gtk.CheckButton TR;

	private global::Gtk.CheckButton ML;

	private global::Gtk.CheckButton MR;

	private global::Gtk.Label CentralLabel;

	private global::Gtk.CheckButton BL;

	private global::Gtk.CheckButton BM;

	private global::Gtk.CheckButton BR;

	private global::Gtk.Button TestButton;

	private global::Gtk.Label worldLabel;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 1200;
		this.HeightRequest = 720;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		this.Resizable = false;
		this.AllowGrow = false;
		this.DefaultWidth = 1200;
		this.DefaultHeight = 720;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.worldNotebook = new global::Gtk.Notebook();
		this.worldNotebook.WidthRequest = 1200;
		this.worldNotebook.HeightRequest = 720;
		this.worldNotebook.CanFocus = true;
		this.worldNotebook.Name = "worldNotebook";
		this.worldNotebook.CurrentPage = 0;
		this.worldNotebook.ShowBorder = false;
		// Container child worldNotebook.Gtk.Notebook+NotebookChild
		this.worldLayout = new global::Gtk.Fixed();
		this.worldLayout.Name = "worldLayout";
		this.worldLayout.HasWindow = false;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.worldImageEventBox = new global::Gtk.EventBox();
		this.worldImageEventBox.WidthRequest = 800;
		this.worldImageEventBox.HeightRequest = 600;
		this.worldImageEventBox.Name = "worldImageEventBox";
		// Container child worldImageEventBox.Gtk.Container+ContainerChild
		this.worldImage = new global::Gtk.Image();
		this.worldImage.WidthRequest = 800;
		this.worldImage.HeightRequest = 600;
		this.worldImage.CanFocus = true;
		this.worldImage.Name = "worldImage";
		this.worldImageEventBox.Add(this.worldImage);
		this.worldLayout.Add(this.worldImageEventBox);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.worldImageEventBox]));
		w2.X = 20;
		w2.Y = 20;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.RunButton = new global::Gtk.Button();
		this.RunButton.Name = "RunButton";
		this.RunButton.UseUnderline = true;
		this.RunButton.FocusOnClick = false;
		this.RunButton.Label = global::Mono.Unix.Catalog.GetString("Run");
		this.worldLayout.Add(this.RunButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.RunButton]));
		w3.X = 20;
		w3.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.StopButton = new global::Gtk.Button();
		this.StopButton.Name = "StopButton";
		this.StopButton.UseUnderline = true;
		this.StopButton.FocusOnClick = false;
		this.StopButton.Label = global::Mono.Unix.Catalog.GetString("Stop");
		this.worldLayout.Add(this.StopButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.StopButton]));
		w4.X = 60;
		w4.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.SaveButton = new global::Gtk.Button();
		this.SaveButton.Name = "SaveButton";
		this.SaveButton.UseUnderline = true;
		this.SaveButton.FocusOnClick = false;
		this.SaveButton.Label = global::Mono.Unix.Catalog.GetString("Save");
		this.worldLayout.Add(this.SaveButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.SaveButton]));
		w5.X = 105;
		w5.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ColonyTypeList = global::Gtk.ComboBox.NewText();
		this.ColonyTypeList.WidthRequest = 200;
		this.ColonyTypeList.Name = "ColonyTypeList";
		this.worldLayout.Add(this.ColonyTypeList);
		global::Gtk.Fixed.FixedChild w6 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ColonyTypeList]));
		w6.X = 850;
		w6.Y = 40;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ColonyTypeLabel = new global::Gtk.Label();
		this.ColonyTypeLabel.Name = "ColonyTypeLabel";
		this.ColonyTypeLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Colony Type</b>");
		this.ColonyTypeLabel.UseMarkup = true;
		this.worldLayout.Add(this.ColonyTypeLabel);
		global::Gtk.Fixed.FixedChild w7 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ColonyTypeLabel]));
		w7.X = 850;
		w7.Y = 20;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ColonyColor = new global::Gtk.ColorButton();
		this.ColonyColor.WidthRequest = 200;
		this.ColonyColor.CanFocus = true;
		this.ColonyColor.Events = ((global::Gdk.EventMask)(784));
		this.ColonyColor.Name = "ColonyColor";
		this.worldLayout.Add(this.ColonyColor);
		global::Gtk.Fixed.FixedChild w8 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ColonyColor]));
		w8.X = 850;
		w8.Y = 100;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ColonyColorLabel = new global::Gtk.Label();
		this.ColonyColorLabel.Name = "ColonyColorLabel";
		this.ColonyColorLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Color</b>");
		this.ColonyColorLabel.UseMarkup = true;
		this.worldLayout.Add(this.ColonyColorLabel);
		global::Gtk.Fixed.FixedChild w9 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ColonyColorLabel]));
		w9.X = 850;
		w9.Y = 80;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ParameterLabel = new global::Gtk.Label();
		this.ParameterLabel.Name = "ParameterLabel";
		this.ParameterLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Parameter</b>");
		this.ParameterLabel.UseMarkup = true;
		this.worldLayout.Add(this.ParameterLabel);
		global::Gtk.Fixed.FixedChild w10 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ParameterLabel]));
		w10.X = 850;
		w10.Y = 140;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ParameterList = global::Gtk.ComboBox.NewText();
		this.ParameterList.WidthRequest = 200;
		this.ParameterList.Name = "ParameterList";
		this.worldLayout.Add(this.ParameterList);
		global::Gtk.Fixed.FixedChild w11 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ParameterList]));
		w11.X = 850;
		w11.Y = 160;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.StringValueLabel = new global::Gtk.Label();
		this.StringValueLabel.Name = "StringValueLabel";
		this.StringValueLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Parameter string value</b>");
		this.StringValueLabel.UseMarkup = true;
		this.worldLayout.Add(this.StringValueLabel);
		global::Gtk.Fixed.FixedChild w12 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.StringValueLabel]));
		w12.X = 850;
		w12.Y = 200;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.StringValue = new global::Gtk.Entry();
		this.StringValue.WidthRequest = 200;
		this.StringValue.CanFocus = true;
		this.StringValue.Name = "StringValue";
		this.StringValue.IsEditable = true;
		this.StringValue.InvisibleChar = '●';
		this.worldLayout.Add(this.StringValue);
		global::Gtk.Fixed.FixedChild w13 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.StringValue]));
		w13.X = 850;
		w13.Y = 220;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ParameterNumericLabel = new global::Gtk.Label();
		this.ParameterNumericLabel.Name = "ParameterNumericLabel";
		this.ParameterNumericLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Parameter numeric value</b>");
		this.ParameterNumericLabel.UseMarkup = true;
		this.worldLayout.Add(this.ParameterNumericLabel);
		global::Gtk.Fixed.FixedChild w14 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ParameterNumericLabel]));
		w14.X = 850;
		w14.Y = 260;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.NumericValue = new global::Gtk.SpinButton(0D, 100D, 1D);
		this.NumericValue.WidthRequest = 200;
		this.NumericValue.CanFocus = true;
		this.NumericValue.Name = "NumericValue";
		this.NumericValue.Adjustment.PageIncrement = 10D;
		this.NumericValue.ClimbRate = 1D;
		this.NumericValue.Digits = ((uint)(2));
		this.NumericValue.Numeric = true;
		this.worldLayout.Add(this.NumericValue);
		global::Gtk.Fixed.FixedChild w15 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.NumericValue]));
		w15.X = 850;
		w15.Y = 280;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.LoadedImage = new global::Gtk.Image();
		this.LoadedImage.WidthRequest = 256;
		this.LoadedImage.HeightRequest = 256;
		this.LoadedImage.Name = "LoadedImage";
		this.worldLayout.Add(this.LoadedImage);
		global::Gtk.Fixed.FixedChild w16 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.LoadedImage]));
		w16.X = 850;
		w16.Y = 364;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.LoadedImageLabel = new global::Gtk.Label();
		this.LoadedImageLabel.Name = "LoadedImageLabel";
		this.LoadedImageLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Image</b>");
		this.LoadedImageLabel.UseMarkup = true;
		this.worldLayout.Add(this.LoadedImageLabel);
		global::Gtk.Fixed.FixedChild w17 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.LoadedImageLabel]));
		w17.X = 850;
		w17.Y = 334;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.LoadImageButton = new global::Gtk.Button();
		this.LoadImageButton.CanFocus = true;
		this.LoadImageButton.Name = "LoadImageButton";
		this.LoadImageButton.UseUnderline = true;
		this.LoadImageButton.Label = global::Mono.Unix.Catalog.GetString("Load Image");
		this.worldLayout.Add(this.LoadImageButton);
		global::Gtk.Fixed.FixedChild w18 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.LoadImageButton]));
		w18.X = 850;
		w18.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.AddImageButton = new global::Gtk.Button();
		this.AddImageButton.CanFocus = true;
		this.AddImageButton.Name = "AddImageButton";
		this.AddImageButton.UseUnderline = true;
		this.AddImageButton.Label = global::Mono.Unix.Catalog.GetString("Add Image");
		this.worldLayout.Add(this.AddImageButton);
		global::Gtk.Fixed.FixedChild w19 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.AddImageButton]));
		w19.X = 950;
		w19.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.Gradient = new global::Gtk.CheckButton();
		this.Gradient.CanFocus = true;
		this.Gradient.Name = "Gradient";
		this.Gradient.Label = global::Mono.Unix.Catalog.GetString("Gradient");
		this.Gradient.DrawIndicator = true;
		this.Gradient.UseUnderline = true;
		this.worldLayout.Add(this.Gradient);
		global::Gtk.Fixed.FixedChild w20 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.Gradient]));
		w20.X = 1055;
		w20.Y = 105;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ShowColonies = new global::Gtk.ToggleButton();
		this.ShowColonies.CanFocus = true;
		this.ShowColonies.Name = "ShowColonies";
		this.ShowColonies.UseUnderline = true;
		this.ShowColonies.FocusOnClick = false;
		this.ShowColonies.Active = true;
		this.ShowColonies.Label = global::Mono.Unix.Catalog.GetString("Show Colonies");
		this.worldLayout.Add(this.ShowColonies);
		global::Gtk.Fixed.FixedChild w21 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ShowColonies]));
		w21.X = 205;
		w21.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ClearButton = new global::Gtk.Button();
		this.ClearButton.CanFocus = true;
		this.ClearButton.Name = "ClearButton";
		this.ClearButton.UseUnderline = true;
		this.ClearButton.FocusOnClick = false;
		this.ClearButton.Label = global::Mono.Unix.Catalog.GetString("Clear");
		this.worldLayout.Add(this.ClearButton);
		global::Gtk.Fixed.FixedChild w22 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ClearButton]));
		w22.X = 155;
		w22.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.NeighborhoodLabel = new global::Gtk.Label();
		this.NeighborhoodLabel.Name = "NeighborhoodLabel";
		this.NeighborhoodLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>Neighborhood</b>");
		this.NeighborhoodLabel.UseMarkup = true;
		this.worldLayout.Add(this.NeighborhoodLabel);
		global::Gtk.Fixed.FixedChild w23 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.NeighborhoodLabel]));
		w23.X = 1060;
		w23.Y = 140;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.TL = new global::Gtk.CheckButton();
		this.TL.Name = "TL";
		this.TL.Label = "";
		this.TL.Active = true;
		this.TL.DrawIndicator = true;
		this.TL.FocusOnClick = false;
		this.worldLayout.Add(this.TL);
		global::Gtk.Fixed.FixedChild w24 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.TL]));
		w24.X = 1060;
		w24.Y = 160;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.TM = new global::Gtk.CheckButton();
		this.TM.Name = "TM";
		this.TM.Label = "";
		this.TM.Active = true;
		this.TM.DrawIndicator = true;
		this.TM.FocusOnClick = false;
		this.worldLayout.Add(this.TM);
		global::Gtk.Fixed.FixedChild w25 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.TM]));
		w25.X = 1090;
		w25.Y = 160;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.TR = new global::Gtk.CheckButton();
		this.TR.Name = "TR";
		this.TR.Label = "";
		this.TR.Active = true;
		this.TR.DrawIndicator = true;
		this.TR.FocusOnClick = false;
		this.worldLayout.Add(this.TR);
		global::Gtk.Fixed.FixedChild w26 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.TR]));
		w26.X = 1120;
		w26.Y = 160;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.ML = new global::Gtk.CheckButton();
		this.ML.Name = "ML";
		this.ML.Label = "";
		this.ML.Active = true;
		this.ML.DrawIndicator = true;
		this.ML.FocusOnClick = false;
		this.worldLayout.Add(this.ML);
		global::Gtk.Fixed.FixedChild w27 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.ML]));
		w27.X = 1060;
		w27.Y = 190;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.MR = new global::Gtk.CheckButton();
		this.MR.Name = "MR";
		this.MR.Label = "";
		this.MR.Active = true;
		this.MR.DrawIndicator = true;
		this.MR.FocusOnClick = false;
		this.worldLayout.Add(this.MR);
		global::Gtk.Fixed.FixedChild w28 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.MR]));
		w28.X = 1120;
		w28.Y = 190;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.CentralLabel = new global::Gtk.Label();
		this.CentralLabel.Name = "CentralLabel";
		this.CentralLabel.LabelProp = global::Mono.Unix.Catalog.GetString("<b>C</b>");
		this.CentralLabel.UseMarkup = true;
		this.worldLayout.Add(this.CentralLabel);
		global::Gtk.Fixed.FixedChild w29 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.CentralLabel]));
		w29.X = 1095;
		w29.Y = 195;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.BL = new global::Gtk.CheckButton();
		this.BL.Name = "BL";
		this.BL.Label = "";
		this.BL.Active = true;
		this.BL.DrawIndicator = true;
		this.BL.FocusOnClick = false;
		this.worldLayout.Add(this.BL);
		global::Gtk.Fixed.FixedChild w30 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.BL]));
		w30.X = 1060;
		w30.Y = 220;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.BM = new global::Gtk.CheckButton();
		this.BM.Name = "BM";
		this.BM.Label = "";
		this.BM.Active = true;
		this.BM.DrawIndicator = true;
		this.BM.FocusOnClick = false;
		this.worldLayout.Add(this.BM);
		global::Gtk.Fixed.FixedChild w31 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.BM]));
		w31.X = 1090;
		w31.Y = 220;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.BR = new global::Gtk.CheckButton();
		this.BR.Name = "BR";
		this.BR.Label = "";
		this.BR.Active = true;
		this.BR.DrawIndicator = true;
		this.BR.FocusOnClick = false;
		this.worldLayout.Add(this.BR);
		global::Gtk.Fixed.FixedChild w32 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.BR]));
		w32.X = 1120;
		w32.Y = 220;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.TestButton = new global::Gtk.Button();
		this.TestButton.CanFocus = true;
		this.TestButton.Name = "TestButton";
		this.TestButton.UseUnderline = true;
		this.TestButton.Label = global::Mono.Unix.Catalog.GetString("Test");
		this.worldLayout.Add(this.TestButton);
		global::Gtk.Fixed.FixedChild w33 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout[this.TestButton]));
		w33.X = 1060;
		w33.Y = 40;
		this.worldNotebook.Add(this.worldLayout);
		// Notebook tab
		this.worldLabel = new global::Gtk.Label();
		this.worldLabel.Name = "worldLabel";
		this.worldLabel.LabelProp = global::Mono.Unix.Catalog.GetString("World");
		this.worldNotebook.SetTabLabel(this.worldLayout, this.worldLabel);
		this.worldLabel.ShowAll();
		this.Add(this.worldNotebook);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.worldImageEventBox.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler(this.OnWorldImageEventBoxButtonPressEvent);
		this.worldImageEventBox.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler(this.OnWorldImageEventBoxButtonReleaseEvent);
		this.worldImageEventBox.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler(this.OnWorldImageEventBoxMotionNotifyEvent);
		this.RunButton.Clicked += new global::System.EventHandler(this.OnRunButtonClicked);
		this.StopButton.Clicked += new global::System.EventHandler(this.OnStopButtonClicked);
		this.SaveButton.Clicked += new global::System.EventHandler(this.OnSaveButtonClicked);
		this.ColonyTypeList.Changed += new global::System.EventHandler(this.OnColonyTypeListChanged);
		this.ParameterList.Changed += new global::System.EventHandler(this.OnParameterListChanged);
		this.StringValue.Changed += new global::System.EventHandler(this.OnStringValueChanged);
		this.NumericValue.ValueChanged += new global::System.EventHandler(this.OnNumericValueValueChanged);
		this.LoadImageButton.Clicked += new global::System.EventHandler(this.OnLoadImageButtonClicked);
		this.AddImageButton.Clicked += new global::System.EventHandler(this.OnAddImageButtonClicked);
		this.ClearButton.Clicked += new global::System.EventHandler(this.OnClearButtonClicked);
		this.TestButton.Clicked += new global::System.EventHandler(this.OnTestButtonClicked);
	}
}
