
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.Notebook worldNotebook;
	private global::Gtk.Fixed worldLayout;
	private global::Gtk.EventBox worldImageEventBox;
	private global::Gtk.Image worldImage;
	private global::Gtk.Button RunButton;
	private global::Gtk.Button StopButton;
	private global::Gtk.Button SaveButton;
	private global::Gtk.Label worldLabel;
	private global::Gtk.Label WorldParametersLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.WidthRequest = 1280;
		this.HeightRequest = 720;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.worldNotebook = new global::Gtk.Notebook ();
		this.worldNotebook.WidthRequest = 1280;
		this.worldNotebook.HeightRequest = 720;
		this.worldNotebook.CanFocus = true;
		this.worldNotebook.Name = "worldNotebook";
		this.worldNotebook.CurrentPage = 0;
		this.worldNotebook.ShowBorder = false;
		// Container child worldNotebook.Gtk.Notebook+NotebookChild
		this.worldLayout = new global::Gtk.Fixed ();
		this.worldLayout.Name = "worldLayout";
		this.worldLayout.HasWindow = false;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.worldImageEventBox = new global::Gtk.EventBox ();
		this.worldImageEventBox.WidthRequest = 800;
		this.worldImageEventBox.HeightRequest = 600;
		this.worldImageEventBox.Name = "worldImageEventBox";
		// Container child worldImageEventBox.Gtk.Container+ContainerChild
		this.worldImage = new global::Gtk.Image ();
		this.worldImage.WidthRequest = 800;
		this.worldImage.HeightRequest = 600;
		this.worldImage.Name = "worldImage";
		this.worldImageEventBox.Add (this.worldImage);
		this.worldLayout.Add (this.worldImageEventBox);
		global::Gtk.Fixed.FixedChild w2 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout [this.worldImageEventBox]));
		w2.X = 20;
		w2.Y = 20;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.RunButton = new global::Gtk.Button ();
		this.RunButton.Name = "RunButton";
		this.RunButton.UseUnderline = true;
		this.RunButton.FocusOnClick = false;
		this.RunButton.Label = global::Mono.Unix.Catalog.GetString ("Run");
		this.worldLayout.Add (this.RunButton);
		global::Gtk.Fixed.FixedChild w3 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout [this.RunButton]));
		w3.X = 20;
		w3.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.StopButton = new global::Gtk.Button ();
		this.StopButton.Name = "StopButton";
		this.StopButton.UseUnderline = true;
		this.StopButton.FocusOnClick = false;
		this.StopButton.Label = global::Mono.Unix.Catalog.GetString ("Stop");
		this.worldLayout.Add (this.StopButton);
		global::Gtk.Fixed.FixedChild w4 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout [this.StopButton]));
		w4.X = 60;
		w4.Y = 640;
		// Container child worldLayout.Gtk.Fixed+FixedChild
		this.SaveButton = new global::Gtk.Button ();
		this.SaveButton.Name = "SaveButton";
		this.SaveButton.UseUnderline = true;
		this.SaveButton.FocusOnClick = false;
		this.SaveButton.Label = global::Mono.Unix.Catalog.GetString ("Save");
		this.worldLayout.Add (this.SaveButton);
		global::Gtk.Fixed.FixedChild w5 = ((global::Gtk.Fixed.FixedChild)(this.worldLayout [this.SaveButton]));
		w5.X = 105;
		w5.Y = 640;
		this.worldNotebook.Add (this.worldLayout);
		// Notebook tab
		this.worldLabel = new global::Gtk.Label ();
		this.worldLabel.Name = "worldLabel";
		this.worldLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("World");
		this.worldNotebook.SetTabLabel (this.worldLayout, this.worldLabel);
		this.worldLabel.ShowAll ();
		// Notebook tab
		global::Gtk.Label w7 = new global::Gtk.Label ();
		w7.Visible = true;
		this.worldNotebook.Add (w7);
		this.WorldParametersLabel = new global::Gtk.Label ();
		this.WorldParametersLabel.Name = "WorldParametersLabel";
		this.WorldParametersLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("World Parameters");
		this.worldNotebook.SetTabLabel (w7, this.WorldParametersLabel);
		this.WorldParametersLabel.ShowAll ();
		this.Add (this.worldNotebook);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 1280;
		this.DefaultHeight = 720;
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.RunButton.Clicked += new global::System.EventHandler (this.OnRunButtonClicked);
		this.StopButton.Clicked += new global::System.EventHandler (this.OnStopButtonClicked);
		this.SaveButton.Clicked += new global::System.EventHandler (this.OnSaveButtonClicked);
	}
}
